### ISSUE TITLE
ReadFrom time out

### ISSUE THREAD

**Issue by wang1219** [kdar/gorawtcpsyn#5]
I use your script, but why does ReadFrom time out? I'm sure that the packet has been sent successfully and can be seen with `tcpdump`
The system of I use is `MacOS`

```
error reading packet:  read ip4 *.*.*.*: i/o timeout
```

**Comment by kdar** [comment]
You may be seeing the packet being sent with tcpdump, but do you see a packet being received? If the destination host you're sending to isn't responding at all, it should just time out like you see.

**Comment by wang1219** [comment]
Thanks for replying, this should be a system issue, everything is OK when I use Centos.
